#!/bin/sh
#
# ABOUT
# Allow whitelist sites
#
######## CONFIG ########
listdir=/etc/pikonek/blocked
########################
touch $listdir/whitelist.list # create empty whitelist in case it does not exist
while IFS= read -r line; 
do # IFS= to prevent read from remove leading or tailing spaces
    grep -v "${line}" $listdir/adware > $listdir/adware.tmp
    grep -v "${line}" $listdir/porn > $listdir/porn.tmp
    grep -v "${line}" $listdir/pisokonekblockedlist > $listdir/pisokonekblockedlist.tmp
    grep -v "${line}" $listdir/blocked.list > $listdir/blocked.list.tmp

    mv $listdir/adware.tmp $listdir/adware
    mv $listdir/porn.tmp $listdir/porn
    mv $listdir/pisokonekblockedlist.tmp $listdir/pisokonekblockedlist
    mv $listdir/blocked.list.tmp $listdir/blocked.list
done < "$listdir/whitelist.list"
echo "OK"

echo -n "[+] Restarting Dnsmasq: "
/etc/init.d/dnsmasq restart
echo "OK!"